### ISSUE TITLE
Coverage report was not generated in good directory

### ISSUE THREAD

**Issue by marmotz** [jubianchi/atoum.js#3]
```
./node_modules/atoum.js/bin/atoum -d tests --loop --coverage --coverage-dir=coverage

...

Code coverage report was generated in /media/data/dev/LSDManager/covershot
```

WTF ?

**Comment by marmotz** [comment]
And my cover is empty :-/

**Comment by jubianchi** [comment]
`--coverage-dir` is not meant to be used to set output directory but the directory in which sources code is.

Let me explain : to generate code coverage report, source has to be instrumented. By default, atoum.js will search for sources in the `lib` directory but you can change that with `--coverage-dir`

Output directory is not configurable ATM.

**Comment by marmotz** [comment]
Oh, ok. Sorry for the mistake
