### ISSUE TITLE
Add assert() method

### ISSUE THREAD

**Issue by Nicolab** [jubianchi/atoum.js#7]
```
this
  .assert('Test instance')
    // ...
```

And output in the doc coverage (covershot).

If it is not too hard to add ?

**Comment by jubianchi** [comment]
Showing test cases description in coverage report (covershot) will not be possible but implementing this feature in the standard cli report would not be too hard.

The description passed to `assert` would be displayed in the report when there are failures.

**Comment by Nicolab** [comment]
Yes is good, it is mainly for the semantic side and separation in the test class.

**Comment by Nicolab** [comment]
:+1:
