### ISSUE TITLE
The report generated by covershot is empty

### ISSUE THREAD

**Issue by Nicolab** [jubianchi/atoum.js#8]
The report generated by covershot is empty, there all html content of html but not the content of the report.

```
node_modules/atoum.js/bin/atoum -d node_modules/noder/tests --coverage=true --coverage-dir=/my/local/path/
```

An idea please ?

**Comment by jubianchi** [comment]
Did you try this : https://github.com/jubianchi/atoum.js/issues/3#issuecomment-26650481 ?

**Comment by Nicolab** [comment]
Thanks :)
